### ISSUE TITLE
Add Calendar feature

### ISSUE THREAD

**Issue by orest22** [caiodias/CleanerSkeeker#6]
Allow a user to save applied job to the calendar. 
- Location and date are requirments

**Comment by caiodias** [comment]
Probably this will help: https://www.andrewcbancroft.com/2016/06/02/creating-calendar-events-with-event-kit-and-swift/ 

Maybe this too: http://stackoverflow.com/questions/28379603/how-to-add-an-event-in-the-device-calendar-using-swift

**Comment by caiodias** [comment]
Added on commit: 249f89cfd301b7e9877c5fbb852c027412f316c7
