### ISSUE TITLE
Fix fail login alert

### ISSUE THREAD

**Issue by orest22** [caiodias/CleanerSkeeker#9]
`Warning: Attempt to present <UIAlertController: 0x7ff029c82010> on <CleanerSeeker.CSTapBar: 0x7ff02c81c950> whose view is not in the window hierarchy!`

**Comment by caiodias** [comment]
Can you describe better the scenario?
I tried to do a wrong login but didn't get this error. For me the alert display normally.

**Comment by orest22** [comment]
@caiodias 
orest@gohikef.nl
123

Gives me that error. 

- It's job poster
- Email wrong
- password ok

**Comment by caiodias** [comment]
Seems like you @orest22 fixed it
